spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tdd_work?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: root
    password: Cjf032912@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    jpa:
      repositories:
        auditing:
          enabled: true

logging:
  level:
    org.hibernate.sql: debug
